In [1]:
import torch

# Trabajando con tensores

In [2]:
torch.__version__

'1.5.1+cu101'

In [3]:
tensor_a = torch.ones(2,2)
print('Tensor 1')
tensor_a

Tensor 1


tensor([[1., 1.],
        [1., 1.]])

In [4]:
# Creando un tensor con valores aleatorios
tensor_b = torch.Tensor(2,2)
# Tensor es una mezcla del metodo "tensor" y "empty"
print('tensor 2')
print(tensor_b)

# Modificando el tensor para tener vlores entre 0 y 1
print('\n tensor 3')
tensor_b.uniform_(0,1)

tensor 2
tensor([[3.6126e-35, 0.0000e+00],
        [3.7835e-44, 0.0000e+00]])

 tensor 3


tensor([[0.1587, 0.5149],
        [0.1964, 0.1913]])

In [5]:
# Alternativa  a los pasos anteriores, crea vector aleatorio uniforme
tensor_c = torch.rand(2,2)
tensor_c

tensor([[0.5994, 0.1552],
        [0.9296, 0.4554]])

### Operaciones basicas

In [6]:
result = tensor_b + tensor_c
result

tensor([[0.7581, 0.6701],
        [1.1260, 0.6466]])

### Dimensiones de un tensor

In [7]:
result.shape

torch.Size([2, 2])

In [8]:
# cambiar la forma
reshaped = result.view(4,1)
reshaped

tensor([[0.7581],
        [0.6701],
        [1.1260],
        [0.6466]])

### Crear un tensor no alaeatorio 

torch.tensor vs torch.Tensor


In [9]:
points = torch.tensor([[1.0,2.0], [3.0,4.0]])
print(points)

tensor([[1., 2.],
        [3., 4.]])


In [10]:
# Puedo acceder a cada uno de los elementos en forma numpy like, o como hashtable
points[0]

tensor([1., 2.])

In [11]:
points[0][1]

tensor(2.)

In [12]:
# Puedo sustituir los valores de la misma forma
points[0][1] = 5

In [13]:
points

tensor([[1., 5.],
        [3., 4.]])

### Ver la forma de almacenamiento de una matriz

In [14]:
points.storage()

 1.0
 5.0
 3.0
 4.0
[torch.FloatStorage of size 4]

In [15]:
points, points.stride()

#Stride is the jump necessary to go from one element to the next one in the specified dimension dim. 

(tensor([[1., 5.],
         [3., 4.]]), (2, 1))

Para pasar del elemento "1" al "3" debo pasar o saltar 2 elementos o posiciones

In [16]:
p_t = points.t()

In [17]:
p_t, p_t.stride()


(tensor([[1., 3.],
         [5., 4.]]), (1, 2))

### Agregar dimensiones con unsqueeze

In [18]:
tensor_x = torch.tensor([1,2,3,4])
print(tensor_x)

tensor([1, 2, 3, 4])


In [19]:
torch.unsqueeze(tensor_x, 0)

tensor([[1, 2, 3, 4]])

In [20]:
torch.unsqueeze(tensor_x, 1)

tensor([[1],
        [2],
        [3],
        [4]])

### Interaccion con numpy

In [21]:
import numpy as np

In [22]:
numpyArray = np.random.rand(2,2)
numpyArray

array([[0.43825603, 0.18545847],
       [0.36177044, 0.74420183]])

In [23]:
from_numpy = torch.from_numpy(numpyArray)
from_numpy

tensor([[0.4383, 0.1855],
        [0.3618, 0.7442]], dtype=torch.float64)

# Representar Datos con Tensores

In [24]:
print(from_numpy)
print(torch.mean(from_numpy))

tensor([[0.4383, 0.1855],
        [0.3618, 0.7442]], dtype=torch.float64)
tensor(0.4324, dtype=torch.float64)


In [25]:
print(torch.mean(from_numpy, dim=0))
print(torch.mean(from_numpy, dim=1))

tensor([0.4000, 0.4648], dtype=torch.float64)
tensor([0.3119, 0.5530], dtype=torch.float64)


### Calcular desviacion estandar

In [26]:
torch.std(from_numpy, dim=1)

tensor([0.1788, 0.2704], dtype=torch.float64)

### Guardando y cardando archivos

In [27]:
torch.save(from_numpy, 'tensor.t')

In [28]:
%ls

sample_data/  tensor.t


In [29]:
load = torch.load('tensor.t')

In [30]:
print(load)

tensor([[0.4383, 0.1855],
        [0.3618, 0.7442]], dtype=torch.float64)


# Trabajando con DataSetes

In [31]:
import pandas as pd

In [68]:
url = "https://raw.githubusercontent.com/amanthedorkknight/fifa18-all-player-statistics/master/2019/data.csv"
dataframe = pd.read_csv(url)
dataframe.head()

Unnamed: 0      ID  ... GKReflexes  Release Clause
0           0  158023  ...        8.0         €226.5M
1           1   20801  ...       11.0         €127.1M
2           2  190871  ...       11.0         €228.1M
3           3  193080  ...       94.0         €138.6M
4           4  192985  ...       13.0         €196.4M

[5 rows x 89 columns]

In [34]:
dataframe.columns

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingT

In [62]:
# Creamos un subset con nuestros datos de interes
subset = dataframe[['Overall', 'Age','International Reputation', 'Weak Foot',
'Skill Moves']].dropna(axis=0, how='any')

subset.head()

Overall  Age  International Reputation  Weak Foot  Skill Moves
0       94   31                       5.0        4.0          4.0
1       94   33                       5.0        4.0          5.0
2       92   26                       5.0        5.0          5.0
3       91   27                       4.0        3.0          1.0
4       91   27                       4.0        5.0          4.0

In [56]:
# Nos quemos con las columnas para el experimento
columns= subset.columns[1:]
columns

Index(['Age', 'International Reputation', 'Weak Foot', 'Skill Moves'], dtype='object')

In [57]:
players = torch.tensor(subset.values).float()
players.shape, players.type()

(torch.Size([18159, 5]), 'torch.FloatTensor')

In [65]:
# Data eliminado columna Overhall para el exerimento
data = players[:,1:]
data, data.shape


(tensor([[31.,  5.,  4.,  4.],
         [33.,  5.,  4.,  5.],
         [26.,  5.,  5.,  5.],
         ...,
         [16.,  1.,  3.,  2.],
         [17.,  1.,  3.,  2.],
         [16.,  1.,  3.,  2.]]), torch.Size([18159, 4]))

In [61]:
# Guarando columna Overhall como target al experimento
target = players[:,0]
target, target.shape

tensor([94., 94., 92.,  ..., 47., 47., 46.])

In [66]:
# Promedio da data
mean = torch.mean(data, dim=0)
mean

tensor([25.1225,  1.1132,  2.9473,  2.3613])

In [67]:
# Desviacion Standar
std = torch.std(data, dim=0)
std

tensor([4.6706, 0.3940, 0.6605, 0.7562])

In [48]:
# Normalizado de la data
norm = (data - mean)/torch.sqrt(std)
norm

tensor([[ 2.7196,  6.1919,  1.2953,  1.8845],
        [ 3.6450,  6.1919,  1.2953,  3.0345],
        [ 0.4060,  6.1919,  2.5258,  3.0345],
        ...,
        [-4.2211, -0.1804,  0.0648, -0.4155],
        [-3.7584, -0.1804,  0.0648, -0.4155],
        [-4.2211, -0.1804,  0.0648, -0.4155]])

In [51]:
# Separando en bueno, malo y promedio
good = data[torch.ge(target, 85)]
average = data[torch.gt(target, 70) & torch.lt(target, 85)]
notSoGood = data[torch.lt(target, 70)]

goodMean = torch.mean(good, dim=0)
averageMean = torch.mean(average, dim=0)
notSoGoodMean = torch.mean(notSoGood, dim=0)

goodMean, averageMean, notSoGoodMean

# ge => greater equal ">="
# gt => greater than ">"
# lt => lower than "<"

(tensor([28.3455,  3.3818,  3.4455,  3.0364]),
 tensor([27.2285,  1.3561,  3.1114,  2.7515]),
 tensor([24.1909,  1.0079,  2.8795,  2.1952]))

In [52]:
for i, args in enumerate(zip(columns, goodMean, averageMean, notSoGoodMean)):
  print('{:25} {:6.2f} {:6.2f} {:6.2f}'.format(*args))

Age                        28.35  27.23  24.19
International Reputation    3.38   1.36   1.01
Weak Foot                   3.45   3.11   2.88
Skill Moves                 3.04   2.75   2.20
